services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "140MB"

  rinha25-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha25-1
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis-server:6379
      - QUARKUS_HTTP_PORT=8080
      - INSTANCE_ID=1
    depends_on:
      - redis-server
    networks:
      - app-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  rinha25-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha25-2
    ports:
      - "8081:8080"
      - "5006:5005"
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis-server:6379
      - QUARKUS_HTTP_PORT=8080
      - INSTANCE_ID=2
    depends_on:
      - redis-server
    networks:
      - app-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "90MB"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./rinha25.conf:/etc/nginx/nginx.conf
    depends_on:
      - rinha25-1
      - rinha25-2
    networks:
      - app-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"  

networks:
  app-network:
    name: app-network
    driver: bridge
  payment-processor:
    external: true 