version: '3.8'
services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

  rinha25:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha25
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis-server:6379
      - QUARKUS_HTTP_PORT=8080
    depends_on:
      - redis-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge