spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs

payment:
  default:
    url: "http://localhost:8001/payments"
  fallback:
    url: "http://localhost:8002/payments"
    
payments-summary:
  default:
    url: "http://localhost:8001/admin/payments-summary"
  fallback:
    url: "http://localhost:8002/admin/payments-summary"